version: '3.0'

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./faas-gateway:~/go/src/github.com/pintjuk/faas/faas-gateway

