version: '3.0'

services:
    gateway:
        build:
            context: ./gateway
        ports:
            - '80:80'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./gateway:/go/src/github.com/pintjuk/faas/gateway
    factorial:
        build:
            context: ./factorial
        labels:
            - "faas.name=factorial"
            - "faas.port=8080"
        volumes:
            - ./factorial:/go/src/github.com/pintjuk/faas/factorial
    addition:
        build:
            context: ./addition
        labels:
            - "faas.name=addition"
            - "faas.port=8080"
        volumes:
            - ./addition:/go/src/github.com/pintjuk/faas/addition
